/**
 * Main App Entry Point
 */
const App = {
    init() {
        console.log("BishiPro Initializing...");
        
        // Load initial data if none exists
        this.checkInitialData();
        
        // Register Global Event Listeners
        this.registerEventListeners();
    },

    checkInitialData() {
        if (Store.getGroups().length === 0) {
            console.log("No groups found. Ready for new setup.");
        }
    },

    registerEventListeners() {
        // Global search member
        const searchInput = document.getElementById('member-search');
        if (searchInput) {
            searchInput.addEventListener('input', (e) => {
                if (typeof Members !== 'undefined') {
                    Members.render(e.target.value);
                }
            });
        }

        // Export Data
        const exportBtn = document.getElementById('export-data-btn');
        if (exportBtn) {
            exportBtn.addEventListener('click', () => this.exportData());
        }

        // Generate PDF Report
        const reportBtn = document.getElementById('generate-report-btn');
        if (reportBtn) {
            reportBtn.addEventListener('click', () => this.generatePDFReport());
        }

        // Section change listeners to refresh data
        document.querySelectorAll('.nav-link[data-section]').forEach(link => {
            link.addEventListener('click', (e) => {
                const section = link.getAttribute('data-section');
                this.refreshSection(section);
            });
        });
    },

    generatePDFReport() {
        const currentMonth = new Date().toLocaleString('default', { month: 'long', year: 'numeric' });
        const transactions = Store.getTransactions().filter(t => t.month === currentMonth);
        const totalCollected = transactions.filter(t => t.type === 'Payment').reduce((s, t) => s + parseFloat(t.amount), 0);
        
        // Simple printable summary
        let reportHTML = `
            <div id="print-report" style="padding: 40px; font-family: sans-serif; color: #333;">
                <h1 style="color: #6366f1; border-bottom: 2px solid #6366f1; padding-bottom: 10px;">BishiPro Monthly Report - ${currentMonth}</h1>
                <div style="display: flex; justify-content: space-between; margin: 30px 0;">
                    <div>
                        <h3>Summary</h3>
                        <p>Total Collected: <strong>$${totalCollected}</strong></p>
                        <p>Report Generated: ${new Date().toLocaleString()}</p>
                    </div>
                </div>
                <h3>Transaction Details</h3>
                <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
                    <thead>
                        <tr style="background: #f1f5f9;">
                            <th style="padding: 12px; border: 1px solid #ddd; text-align: left;">Date</th>
                            <th style="padding: 12px; border: 1px solid #ddd; text-align: left;">Member</th>
                            <th style="padding: 12px; border: 1px solid #ddd; text-align: left;">Type</th>
                            <th style="padding: 12px; border: 1px solid #ddd; text-align: left;">Amount</th>
                        </tr>
                    </thead>
                    <tbody>
                        ${transactions.map(t => `
                            <tr>
                                <td style="padding: 12px; border: 1px solid #ddd;">${new Date(t.date).toLocaleDateString()}</td>
                                <td style="padding: 12px; border: 1px solid #ddd;">${t.memberName}</td>
                                <td style="padding: 12px; border: 1px solid #ddd;">${t.type}</td>
                                <td style="padding: 12px; border: 1px solid #ddd;">$${t.amount}</td>
                            </tr>
                        `).join('')}
                    </tbody>
                </table>
                <p style="margin-top: 50px; font-size: 0.8rem; color: #94a3b8; text-align: center;">Generated by BishiPro Premium Management System</p>
            </div>
        `;

        const printWindow = window.open('', '_blank');
        printWindow.document.write(`
            <html>
                <head><title>BishiPro Report - ${currentMonth}</title></head>
                <body>${reportHTML}</body>
            </html>
        `);
        printWindow.document.close();
        printWindow.print();
    },

    refreshSection(section) {
        switch(section) {
            case 'dashboard':
                if (typeof Dashboard !== 'undefined') Dashboard.render();
                break;
            case 'groups':
                if (typeof Groups !== 'undefined') Groups.render();
                break;
            case 'members':
                if (typeof Members !== 'undefined') Members.render();
                break;
            case 'collections':
                if (typeof Collections !== 'undefined') Collections.render();
                break;
            case 'draw':
                if (typeof Draw !== 'undefined') Draw.render();
                break;
            case 'history':
                this.renderHistory();
                break;
            case 'reports':
                if (typeof Dashboard !== 'undefined') Dashboard.renderReports();
                break;
            case 'settings':
                this.loadSettings();
                break;
        }
    },

    renderHistory() {
        const transactions = Store.getTransactions();
        const body = document.getElementById('history-body');
        body.innerHTML = '';

        if (transactions.length === 0) {
            body.innerHTML = '<tr><td colspan="5" class="empty-msg">No transactions found</td></tr>';
            return;
        }

        transactions.forEach(t => {
            const tr = document.createElement('tr');
            tr.innerHTML = `
                <td>${new Date(t.date).toLocaleDateString()}</td>
                <td>${t.memberName}</td>
                <td><span class="status-pill status-${t.type.toLowerCase()}">${t.type}</span></td>
                <td>$${t.amount}</td>
                <td>${t.description}</td>
            `;
            body.appendChild(tr);
        });
    },

    loadSettings() {
        const user = Store.getCurrentUser();
        if (user) {
            document.getElementById('settings-name').value = user.name;
            document.getElementById('settings-email').value = user.email;
        }
    },

    exportData() {
        const data = {
            users: Store.getUsers(),
            groups: Store.getGroups(),
            members: Store.getMembers(),
            transactions: Store.getTransactions(),
            drawHistory: Store.getDrawHistory()
        };

        const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `bishipro_backup_${new Date().toISOString().split('T')[0]}.json`;
        a.click();
        UI.showToast('Data exported successfully!');
    }
};

// Start the app
document.addEventListener('DOMContentLoaded', () => App.init());
